export enum ScotlandRegionNhs  {
    nhs_ayrshire_arran = 'nhs_ayrshire_arran',
    nhs_borders = 'nhs_borders',
    nhs_dumfries_galloway = 'nhs_dumfries_galloway',
    nhs_fife = 'nhs_fife',
    nhs_forth_valley = 'nhs_forth_valley',
    nhs_grampian = 'nhs_grampian',
    nhs_greater_glasgow_clyde = 'nhs_greater_glasgow_clyde',
    nhs_highland = 'nhs_highland',
    nhs_lanarkshire = 'nhs_lanarkshire',
    nhs_lothian = 'nhs_lothian',
    nhs_orkney = 'nhs_orkney',
    nhs_shetland = 'nhs_shetland',
    nhs_tayside = 'nhs_tayside',
    nhs_western_isles_scotland = 'nhs_western_isles_scotland',
    golden_jubilee_nationalhospital = 'golden_jubilee_nationalhospital',
    scotland = 'scotland',
}
