export enum ERROR_CODES {
  SERVER_EXCEPTION = 'SERVER_EXCEPTION',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  ASSERTION_ERROR = 'ASSERTION_ERROR',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_PASSWORD_NOT_MATCH = 'USER_PASSWORD_NOT_MATCH',
  AUTHENTICATION_TOKEN_MISSING = 'AUTHENTICATION_TOKEN_MISSING',
  WRONG_AUTHENTICATION_TOKEN = 'WRONG_AUTHENTICATION_TOKEN',
  REDUNDANT_UPDATE = 'REDUNDANT_UPDATE',
  ACCESS_CONTROL = 'ACCESS_CONTROL',
  INVALID_QUERY_PARAMETERS = 'INVALID_QUERY_PARAMETERS',

  CSV_PARSE_ERROR = 'CSV_PARSE_ERROR',
  FILE_NOT_AVAILABLE = 'FILE_NOT_AVAILABLE',

  PAGE_BOOKMARK = 'PAGE_BOOKMARK',
  SEARCH_ERROR = 'SEARCH_ERROR',

  ID_DOES_NOT_EXIST = 'ID_DOES_NOT_EXIST',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
}
