version: "3.8"

services:
  node:
    container_name: rampvis-data-api
    build:
      context: .
      dockerfile: data-api/Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./data-api:/usr/rampvis-api/data-api
      - /usr/rampvis-api/data-api/node_modules
    ports:
      - 2000:2000
    links:
      - mongo
      - es01
      - es02
      - es03

  flask:
    container_name: rampvis-stat-api
    build:
      context: .
      dockerfile: stat-api/Dockerfile
    volumes:
      - ./api-python:/usr/rampvis-api/api-python
    ports:
      - 3000:3000
    links:
      - mongo

  mongo:
    container_name: rampvis-api-mongo
    image: mongo:latest
    volumes:
      - ./docker_seeder/data:/usr/rampvis-api/seed_data
      - ./docker_seeder/scripts:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - mongo
  #
  # elasticsearch
  #
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - elastic
  
  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
  mongo:
    driver: bridge
