version: '3'

services:
  app:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 2000:2000
    environment:
      NODE_ENV: development

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: scrc_internal
    volumes:
      - ./mongo_db_data:/data/db
      - ./scripts/seeder.js:/docker-entrypoint-initdb.d/1_seeder.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_AUTH_DATABASE: scrc_internal
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

