version: "3"

services:
  #
  # mongodb
  #
  mongodb01:
    image: mongo:4.4.11
    restart: always
    container_name: mongodb01
    volumes:
      - mongodata01:/data/db
    expose:
      - "27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rsmongo",
        "--bind_ip_all",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    ports:
      - 27017:27017
    networks:
      - rampvis-api-net

  mongodb02:
    image: mongo:4.4.11
    restart: always
    container_name: mongodb02
    volumes:
      - mongodata02:/data/db
    expose:
      - "27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rsmongo",
        "--bind_ip_all",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    networks:
      - rampvis-api-net

  mongodb03:
    image: mongo:4.4.11
    restart: always
    container_name: mongodb03
    volumes:
      - mongodata03:/data/db
    expose:
      - "27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rsmongo",
        "--bind_ip_all",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    networks:
      - rampvis-api-net

  mongosetup:
    image: "mongo-setup"
    build: "./setup-scripts"
    container_name: "mongosetup"
    depends_on:
      - mongodb01
    volumes:
      - mongostatus:/data/
    networks:
      - rampvis-api-net

  #
  # elasticsearch
  #
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - rampvis-api-net

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - rampvis-api-net

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    networks:
      - rampvis-api-net

  #
  # kibana
  #
  kib01:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - rampvis-api-net

  #
  #
  #
  data-api:
    hostname: data-api
    container_name: data-api
    build:
      context: ./data-api
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - 4010:4010
    volumes:
      - ./data-api:/usr/src/data-api # mount the data-api folder
      - ./data:/usr/src/data # mount the data
    networks:
      - rampvis-api-net

#
# volumes
#
volumes:
  esdata01:
  esdata02:
  esdata03:
  mongodata01:
  mongodata02:
  mongodata03:
  mongostatus:

#
# networks
#
networks:
  rampvis-api-net:
    driver: bridge
