version: "3"

services:
  #
  # mongodb
  #
  mongodb01:
    image: mongo:4.4.11
    restart: always
    container_name: mongodb01
    volumes:
      - mongodata01:/data/db
    expose:
      - "27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rsmongo",
        "--bind_ip_all",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    ports:
      - 27017:27017
    # networks:
    #   - rampvis-api-network

  mongodb02:
    image: mongo:4.4.11
    restart: always
    container_name: mongodb02
    volumes:
      - mongodata02:/data/db
    expose:
      - "27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rsmongo",
        "--bind_ip_all",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    # networks:
    #   - rampvis-api-network

  mongodb03:
    image: mongo:4.4.11
    restart: always
    container_name: mongodb03
    volumes:
      - mongodata03:/data/db
    expose:
      - "27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rsmongo",
        "--bind_ip_all",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    # networks:
    #   - rampvis-api-network

  #
  # elasticsearch
  #
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    # networks:
    #   - rampvis-api-network

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    # networks:
    #   - rampvis-api-network

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    # networks:
    #   - rampvis-api-network

  #
  # kibana
  #
  kib01:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    # networks:
    #   - rampvis-api-network

#
# volumes
#
volumes:
  esdata01:
  esdata02:
  esdata03:
  mongodata01:
  mongodata02:
  mongodata03:

#
# networks
#
# networks:
#   rampvis-api-net:
#     driver: bridge
networks:
  default:
    external: true
    name: rampvis-api-network
