name: ramp-vis-api
channels:
  - anaconda
  - defaults
dependencies:
  - apscheduler=3.6.3
  - cryptography=2.9.2
  - flask=1.1.2
  - flask-cors=3.0.8
  - jinja2=2.11.2
  - matplotlib=3.2.2
  - numpy=1.18.5
  - pandas=1.0.4
  - python=3.8.3
  - scikit-image=0.16.2
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - pip:
    - blueprint==3.4.2
    - pyjwt==1.7.1
    - data-pipeline-api
    - fsspec
    - flask_caching==1.9.0
    - neo4j==4.1.1
    - py2neo==2020.7b8

