name: rampvis-api
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cryptography
  - jinja2
  - matplotlib
  - numpy
  - pandas
  - scikit-image
  - scikit-learn
  - scipy
  - pip:
      - flask
      - flask_cors
      - flask_caching
      - flask_restful
      - flask_injector
      - pyjwt
      - apscheduler
      - fsspec
      - data-pipeline-api
      - elasticsearch
      - pymongo
      - dnspython
      - neo4j
      - autopep8
      - pytest
      - marshmallow
      - pyamg
