name: rampvis-api
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cryptography=2.9.2
  - flask=1.1.2
  - flask-cors=3.0.8
  - jinja2=2.11.2
  - matplotlib=3.2.2
  - numpy=1.18.5
  - pandas=1.0.4
  - python=3.8.3
  - scikit-image=0.16.2
  - scikit-learn=0.24.1
  - scipy=1.5.0
  - pip:
      - flask_cors==3.0.10
      - pyjwt==1.7.1
      - apscheduler==3.6.3
      - flask_caching==1.9.0
      - fsspec==0.8.4
      - data-pipeline-api
      - neo4j==4.1.1
      - marshmallow==3.9.0
      - flask_injector==0.12.3
      - pymongo
      - dnspython
      - elasticsearch
      - autopep8
      - seaborn